Repository GEWIS/gewisweb, pull requests merged in 2020-07, with the labels that each got.

#1021 Fix missing poll vote view and incorrect vote casting
  module/Frontpage/src/Frontpage/Controller/PollController.php
Labels: enhancement

#826 Fix for #813: jobs cannot be made inactive
  module/Company/src/Company/Form/FixedKeyDictionaryCollection.php
  module/Company/src/Company/Model/CompanyJobPackage.php
  module/Company/src/Company/Service/Company.php
Labels: in testing

#1009 implement job deletion
  module/Company/config/module.config.php
  module/Company/src/Company/Controller/AdminController.php
  module/Company/src/Company/Mapper/Job.php
  module/Company/src/Company/Service/Company.php
  module/Company/view/company/admin/edit-package.phtml
Labels: enhancement, feature, in testing
