Repository GEWIS/gewisweb, pull requests merged in 2021-08, with the labels that each got.

#1177 Fix issue with being unable to logout with persisting sessions
  module/User/src/Authentication/AuthenticationService.php
  module/User/src/Authentication/Storage/Session.php
  module/User/src/Service/User.php
Labels: Priority: High, For: Backend, Status: In Testing

#1190 Fix `LocalFileReader` not returning `Stream` for downloadable files
  module/Decision/src/Controller/DecisionController.php
  module/Decision/src/Controller/FileBrowser/FileNode.php
  module/Decision/src/Controller/FileBrowser/FileReader.php
  module/Decision/src/Controller/FileBrowser/LocalFileReader.php
Labels: Status: In Testing

#1191 Fixed creation of subalbums
  module/Photo/src/Listener/AlbumDate.php
Labels: Type: Bug, For: Backend

#1201 Fixed a strict type bug that causes issues with user registration
  module/User/src/Service/User.php
Labels: Type: Bug, Priority: High, For: Backend

#1206 Fixed CLI shortcut ./web
  bootstrap.php
  web
Labels: Type: Bug
