Repository GEWIS/gewisweb, pull requests merged in 2021-07, with the labels that each got.

#1111 Fix public archive cronjob
  .dockerignore
  .gitignore
  docker/web/development/crontab
  docker/web/development/docker-entrypoint.sh
  docker/web/production/crontab
  docker/web/production/docker-entrypoint.sh
  publicarchive.sh
Labels: For: Backend

#1117 Made use of Infima API endpoint
  docker/nginx/nginx.conf
  module/Application/Module.php
  module/Application/src/Application/Service/Legacy.php
  module/Application/src/Application/View/Helper/Infima.php
  module/Application/view/partial/footer.phtml
  module/Frontpage/view/frontpage/frontpage/home.phtml
Labels: For: Frontend, Priority: High

#1120 Fix premature session invalidation
  module/User/src/User/Authentication/Storage/Session.php
Labels: For: Backend, Priority: High

#1146 Added a PhpStan shortcut to evaluate PR changes & moved PhpStan files
  .gitignore
  Makefile
  phpstan.neon
  phpstan/phpstan-baseline.neon
  phpstan/phpstan-om.php
  phpstan/phpstan-sm.php
Labels: Type: Enhancement
