Repository GEWIS/gewisweb, pull requests merged in 2022-07, with the labels that each got.

#1479 Dependencies update 2022-06b
  composer.lock
  docker/glide/composer.lock
  module/Decision/src/Model/Enums/MembershipTypes.php
  module/User/src/Model/Enums/JWTClaims.php
  package-lock.json
Labels: Type: Dependencies

#1488 Updated dependencies
  Makefile
  composer.lock
  composer.phar
  docker/glide/composer.lock
  docker/glide/composer.phar
  package-lock.json
Labels: For: Backend, For: Frontend, Type: Dependencies, Module: Application

#1491 Update menu for housing page
  module/Application/view/partial/main-nav.phtml
Labels: For: Frontend, Module: Application, Module: Frontpage
